### ISSUE TITLE
Documentation link URL for Workers

### ISSUE THREAD

**Issue by lozadaOmr** [nvie/rq#890]
On the URL `http://python-rq.org/docs/`

Link to see the workers page has a duplicate 'docs'

# The worker
To learn about workers, see the [workers](http://python-rq.org/docs/docs/workers/) documentation.

--- 
Should it be just `http://python-rq.org/docs/workers/`

**Comment by selwin** [comment]
This is fixed.

**Comment by neoatmatrix** [comment]
Link is not fixed, it is still taking to http://python-rq.org/docs/docs/workers/

**Comment by selwin** [comment]
@neoatmatrix can you give me the URL that contains that link?
