### ISSUE TITLE
0.9.0 traceback

### ISSUE THREAD

**Issue by rosselliott** [nvie/rq#899]
Ok, so we updated from 0.8.2 to 0.9.0 and got the following when one of our rq workers was restarted.

`Traceback (most recent call last):
  File "/home/ice/.local/share/virtualenvs/analytics/bin/rq", line 11, in <module>
    sys.exit(main())
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/cli/cli.py", line 73, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/cli/cli.py", line 202, in worker
    cleanup_ghosts(cli_config.connection)
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/contrib/legacy.py", line 25, in cleanup_ghosts
    for worker in Worker.all(connection=conn):
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/worker.py", line 109, in all
    for key in reported_working]
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/worker.py", line 136, in find_by_key
    worker.refresh()
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/worker.py", line 543, in refresh
    self.last_heartbeat = utcparse(as_text(last_heartbeat))
  File "/home/ice/.local/share/virtualenvs/analytics/local/lib/python2.7/site-packages/rq/utils.py", line 169, in utcparse
    return datetime.datetime.strptime(string, _TIMESTAMP_FORMAT)
TypeError: must be string, not None`

My assumption here is that it cannot find the last_heartbeat timestamp when it starts up but rather than checking for it it then tries to parse None and falls over.

**Comment by mredar** [comment]
getting this same error due to the upgrade....

**Comment by davidstults** [comment]
We are getting this error as well.  Downgraded back to 0.8.2.

**Comment by selwin** [comment]
Will look at this soon.

**Comment by selwin** [comment]
This should be fixed in https://github.com/nvie/rq/commit/7b9c3b6b663508814b36dc2ffc0f792eca642180 . Additionally, version 0.9.1 is also live on PyPI. Please check the latest version and let me know if there's other issues :)

**Comment by tudoanh** [comment]
Hmm, I'm using version 0.9.1 but still getting that error. Hope you'll fix it soon.  
Btw, thanks for great lib.

**Comment by adam-via** [comment]
I also get the same error on 0.9.1, but if I uninstall rq and reinstall rq then it seems to work fine.
